const Map<String, String> appStringsEn = {
  'appName': 'UnitPro',
  'appTagline': 'Convert any unit, instantly.',
  'loading': 'Loading',
  'shop': 'Shop',
  'you': 'Settings',
  'settings': 'Settings',
  'navConverter': 'Converter',
  'navFavorites': 'Favorites',
  'navHistory': 'History',
  'navShop': 'Shop',

  'unitConverter': 'Unit Converter',
  'quickAccess': 'Quick Access',
  'from': 'From',
  'to': 'To',
  'swap': 'Swap',
  'copyResult': 'Copied',
  'enterValue': 'Enter a value',
  'lockedCategory': 'Unlock in Shop',
  'proBadge': 'PRO',

  'catLength': 'Length',
  'catWeight': 'Weight',
  'catTemperature': 'Temperature',
  'catArea': 'Area',
  'catVolume': 'Volume',
  'catSpeed': 'Speed',
  'catTime': 'Time',
  'catData': 'Data',

  'favorites': 'Favorites',
  'favoritesEmpty': 'Star a pair to keep it here.',
  'history': 'History',
  'historyEmpty': 'Your conversions will land here.',
  'clearHistory': 'Clear history',
  'addedFavorite': 'Saved to Favorites',
  'removedFavorite': 'Removed',

  'statsConverts': '{n} conversions this week',
  'statsStreak': '{n}-day streak',
  'statsFavorites': '{n} saved pairs',

  'next': 'Next',
  'skipOnboard': 'Skip',
  'getStarted': 'Start converting',
  'onboardTitle1': 'Any unit, one tap',
  'onboardDesc1': 'Length, weight, temperature, area — swap and go.',
  'onboardTitle2': 'Keep what you use',
  'onboardDesc2': 'Star a pair. History remembers the rest.',
  'onboardTitle3': 'Unlock the rest',
  'onboardDesc3': 'Volume, speed, time, and data live in the Pro pack.',

  'shopTagline': 'Themes, styles, and extra units',
  'shopVipBadge': 'PRO',
  'shopCatalog': 'Catalog',
  'shopMore': 'More items',
  'shopPacks': 'Coin packs',
  'shopToday': 'Today',
  'shopMenuAll': 'All',
  'shopMenuPremium': 'Pro',
  'shopMenuThemes': 'Themes',
  'shopThemePremiumBadge': 'PRO',
  'shopMenuBackgrounds': 'Backgrounds',
  'shopMenuSkins': 'Styles',
  'shopMenuFeatures': 'Features',
  'shopRemoveAds': 'Remove ads',
  'shopRemoveAdsDesc': 'Hide coin prompts. Conversions stay on this device.',
  'shopThemeDefault': 'Violet',
  'shopThemeDefaultDesc': 'The original purple',
  'shopBgDefault': 'True black',
  'shopBgDefaultDesc': 'Clean dark background',
  'shopSkinDefault': 'Rounded cards',
  'shopSkinDefaultDesc': 'Soft corners, no glow',
  'shopThemeEmerald': 'Aurora Teal',
  'shopThemeEmeraldDesc': 'Jewel teal glow on deep forest black',
  'shopThemeGold': 'Gilded Amber',
  'shopThemeGoldDesc': 'Champagne gold on warm night',
  'shopThemeMidnight': 'Nebula Violet',
  'shopThemeMidnightDesc': 'Electric lilac on ink',
  'shopBgForest': 'Graphite',
  'shopBgForestDesc': 'A deeper charcoal',
  'shopBgAurora': 'Slate',
  'shopBgAuroraDesc': 'Cool blue-grey',
  'shopBgSunset': 'Dusk',
  'shopBgSunsetDesc': 'Warm night wash',
  'shopSkinSoft': 'Soft cards',
  'shopSkinSoftDesc': 'Larger corner radius',
  'shopSkinNeon': 'Glow edge',
  'shopSkinNeonDesc': 'A thin purple outline',
  'shopFeatPaper': 'Pro units',
  'shopFeatPaperDesc': 'Volume, speed, time, and data',
  'shopFeatSpaces': 'High precision',
  'shopFeatSpacesDesc': 'Up to 10 decimal places',
  'shopFeatDoubleCoins': 'Double coins',
  'shopFeatDoubleCoinsDesc': 'Earn 2× from daily rewards',

  'buy': 'Buy',
  'owned': 'Owned',
  'equipped': 'Active',
  'equip': 'Use',
  'resetDefault': 'Reset default',
  'resetDefaultDesc': 'Violet theme, true black, rounded cards',
  'purchaseSuccess': 'Unlocked in UnitPro',
  'purchaseFailed': 'Purchase failed. Try again.',
  'coinsAdded': 'Coins added',
  'coinsAddedWithBonus': 'Coins added — bonus included',
  'alreadyOwned': 'Already yours',
  'insufficientCoins': 'Not enough coins',
  'applied': 'Applied',
  'apply': 'Apply',
  'active': 'Active',
  'unlocked': 'Unlocked',
  'restorePurchases': 'Restore purchases',
  'removeAdsUnlocked': 'Ads are hidden',
  'dailyRewardClaimed': 'Today’s coins are in',
  'spinRewardEarned': 'You won a spin reward',
  'levelRewardEarned': 'Coins for converting',
  'claimDaily': 'Claim',
  'dailyClaimed': 'Claimed',
  'dailyReward': 'Daily coins',
  'loginStreak': '{days}-day streak',
  'spinWheel': 'Lucky spin',
  'spinUsed': 'Come back tomorrow',
  'earnCoins': 'Daily rewards',
  'earnCoinsDesc': 'Claim the day, spin, or buy a pack',
  'spinNow': 'Spin',
  'bestValueBadge': 'Best',

  'soundEffects': 'Soft sounds',
  'darkMode': 'Dark mode',
  'privacyPolicy': 'Privacy policy',
  'privacyPolicyTitle': 'Your conversions stay on the phone',
  'privacyPolicyBody': 'UnitPro keeps conversions, favorites, and coins on this device. We do not ask for an account. Purchases go through the store. The remote config only checks whether billing should stay on.',
  'buyCoins': 'Buy coin packs',
  'buyCoinsDesc': 'Instant coins via Google Play',
  'earnCoinsHint': 'Or earn free coins from the daily reward',
  'coinBalanceLabel': 'Your balance',
  'firstPurchaseBadge': '+50% bonus',
  'purchasePromoDesc': 'Get {coins} coins — enough for Pro units.',
  'hotDealBadge': 'HOT',
  'coinBonusExtra': '{base} + {bonus} bonus',
  'coinPack': 'Pack {num}',
  'openingBilling': 'Opening Google Play…',
  'configTimeout': 'Connection timed out',
  'configNetworkError': 'Network error',
  'billingUnavailable': 'Billing unavailable',
  'productsNotFound': 'Products not configured yet',
  'promoTitle': 'Need more coins?',
  'promoSubtitle': 'Packs unlock Pro units and themes',
  'promoBuy': 'Buy coins',
  'promoBuyShort': 'Buy',
  'promoCompactTitle': 'Need coins?',
  'promoHotDealDesc': 'Pack {pack} is {percent}% off this week.',
  'promoHotDeal': 'Weekly deal',
  'promoBuyNow': 'Buy now',
  'promoUnlockRemaining': '{count} coins to next unlock',
  'promoUnlockReady': 'Ready to unlock in Shop',
  'coinEarned': '+{amount} coins',
  'coinRewardSub': 'Balance: {balance}',
  'getMorePoints': 'Get coins',
  'insufficientCoinsDetail': 'You need {count} more coins for this item.',
  'billingDisabled': 'In-app purchases temporarily unavailable',
  'about': 'About',
  'version': 'Version {v}',
};
